### ISSUE TITLE
[JOSS] consolidate doc requirement files

### ISSUE THREAD

**Issue by sappelhoff** [powerfulbean/mTRFpy#10]
- xref: https://github.com/openjournals/joss-reviews/issues/5657

IMHO, these 3 files should just be one file, called `docs/requirements.txt`:

- https://github.com/powerfulbean/mTRFpy/blob/0df8aa66c23e480829336889b977ff7bff9e1c54/docs/requirements.in#L1
- https://github.com/powerfulbean/mTRFpy/blob/0df8aa66c23e480829336889b977ff7bff9e1c54/requirements_rtd.txt#L1
- https://github.com/powerfulbean/mTRFpy/blob/0df8aa66c23e480829336889b977ff7bff9e1c54/docs/requirements.txt#L1

**Comment by OleBialas** [comment]
removed requirements_rdt.txt and requirements.in
