### ISSUE TITLE
return best_regularization in the TRF.test

### ISSUE THREAD

**Issue by powerfulbean** [powerfulbean/mTRFpy#19]
I think it is still a good idea to return the best_regularization, because it is decided based on the mse of the training fold but we just return the r and mse for  the testing fold

**Comment by OleBialas** [comment]
The reason I took it out is that I can not really imagine a situation where one might want this output, If you disagree about that I am happy to discuss putting it back in

**Comment by powerfulbean** [comment]
seems that returning it would potentially be helpful when people want to choose a regularization parameter for permutation test #21
