### ISSUE TITLE
Multi-channel mTRFs ?

### ISSUE THREAD

**Issue by mamadyonline** [powerfulbean/mTRFpy#28]
Hello,

First of all, thanks for this great initiative.

I am trying to use your library to perform an mTRF analysis, but I am encountering some issues. My understanding is that, it should be able to handle cases where you have multiple features AND multiple channels.

So for example, if I have data where there is only say, one feature and multi-channel brain output say, 5, I should not have an issue to use your library. But I am facing this issue. And I think it is because of the data verification located precisely at lines 50-53. In my case, this fails since I have the following: for every trial, my input has dimension (1,) (only one feature, this would have been (1, N) for N features) and my output has dimension (128,) (for 128 channels, this would have been (128, N) for N features and 128 channels).

Is there any way to make this example work ?

To replicate it, you can use the following sample data:

stimulus = array(
      [[-0.04975775],
       [-0.04975775],
       [-0.04975775],
       [-0.04975775],
       [-0.04975775]]
)
response = array(
       [[ 2.14178848,  1.66653419, -0.46084577, -0.75411433, -1.61435759],
       [ 2.21314073,  1.86260605, -0.23229724, -0.75092149, -1.85647023],
       [ 2.14174962,  1.98497665, -0.07170469, -0.9689309 , -2.16715288],
       [ 1.92276275,  1.92720366, -0.01842625, -1.10627818, -2.35880566],
       [ 1.55253088,  1.63285232, -0.05710639, -1.19575059, -2.18979287]]
)

Thank you very much. 

P.S. Aside, I know it is a lot of work for you, I also noticed that the docstrings of the function `_check_data` is not up to date, possibly due some changes in prototypes.

**Comment by powerfulbean** [comment]
Hi,

Thank you very much for your interest in mTRFpy and providing your feedbacks! 

Based on your description, do you mean you got the following message:
"Stimulus and response must have the same number of trials and the same number of samples in each trial!" ?

I just tried the following code based on the sample data you provided, and it works:

`oTRF = TRF()
oTRF.train(stimulus, response, fs = 2, tmin = 0, tmax = 0.6, regularization = 0.1)`

May I ask if you would like to shared the error message you got and the code you tried?

Thank you very much again!

Best,
Jin

**Comment by mamadyonline** [comment]
Thank you very much for the quick reply.

You got it, that is part of the errors that I am having ("Stimulus and response must have the same number of trials and the same number of samples in each trial!"). But the final error message is this: "Data list is too short".

This is curious because I systematically get the above error, but I am using the crossval function coupled with a TRF model (defined following your basic example in the documentation). Additionally, I am giving it a list of regularization values instead one value. 

So I rerun your code, and yes it works without any errors. I went from this to replicate the exact error I have with other parameters of my setting. Two things: I have a sampling frequency of 128, this alone gives to my error above. If I keep a sampling frequency of 2 as in your example, but give a list as the regularization parameter value, it also crashes with the same error.

I am surely missing something. Is the `fs` parameter not the sampling rate of the data ? Why a list of regularization values does not seem to work ?

Best,
MN

**Comment by OleBialas** [comment]
If you pass a list of regularization values, `TRF.train` will test them and pick the best one. Testing is done via cross-validation, which means that the TRF is trained on one part of your data and evaluated on another.  The problem in your example is that there is only a single trial (i.e. one array) and so there is no way to split the data. You need a list that contains at least two (although at least 10 would be better) trials. You can use `numoy.array_split` to split an array into equally long segments.
@powerfulbean: The "Data list is too short" warning should be more informative, and we should make it more explicit that an array is a single trial

**Comment by powerfulbean** [comment]
Hi MN,

Thank you very much for your detailed description. You are right on the 'fs' parameter, it is the sampling rate. I set fs = 2 because I don;t know the sampling rate of the sample array. And following Ole's answer, by default the cross-validation is in leave-one-out mode.

Best,
Jin

**Comment by powerfulbean** [comment]
> If you pass a list of regularization values, `TRF.train` will test them and pick the best one. Testing is done via cross-validation, which means that the TRF is trained on one part of your data and evaluated on another. The problem in your example is that there is only a single trial (i.e. one array) and so there is no way to split the data. You need a list that contains at least two (although at least 10 would be better) trials. You can use `numoy.array_split` to split an array into equally long segments. @powerfulbean: The "Data list is too short" warning should be more informative, and we should make it more explicit that an array is a single trial

Agree totally.

**Comment by mamadyonline** [comment]
Hi Ole, Hi back Jin,

Following Ole's comment and suggestions, I am now able to run my code as desired. Using the np.array_split solves the problem for the error message "Data list is too short". 

And thanks Jin for the feedback on the crossvalidation, I am well aware of this problem. So I also tested with different k values, especially 5, and it all works fine. But only if I use the train function and not the crossval one. In the latter, I get the following error message: operands could not be broadcast together with sahpes... The error is located at line 293 of _crossval function from the stats module. My guess is that it is probably only expecting integers or floats and not array for the regularization parameter. I may be wrong though.

Thanks to both of you. 

MN

**Comment by mamadyonline** [comment]
Me again. 

Even though using `np.array_split` does work, I wonder if this is what I actually need. In my initial data example, there is one array arranged along the time axis. So actually each example constitutes the input at one time point. If I use the `np.array_split`, I wonder if by creating the different "trials" this way does not make me loose the temporality of my initial data down the line when applying crossval. Can you clarify me on this part please ? And a dumb question, what do you mean by trials ? If I record a patient in one long block, does this qualify for one trial in your vocabulary ? Or is it something else ?

Thank you very much again

**Comment by OleBialas** [comment]
Regarding your first question:
Yes, `crossval` only takes a scalar value for regularization. If you want to cross-validate while testing out multiple regularization values, you have to use the `nested_crossval` function. There is a [section in the docs](https://mtrfpy.readthedocs.io/en/latest/optimization.html#more-overfitting) explaining why this is necessary.

Regarding your second question:
By trial, we simply mean a unit of data. Trials can be grouped into sets during cross-validation or randomized during permutation, but the data within one trial will never be split or altered in any way. Most studies record data in trials that range from a few seconds to several minutes, so their data will be arranged in trials naturally. However, if you recorded the data in one continuous stream, you may just split the array into trials before analysis. This should not be an issue as long as the mapping between stimulus and response is preserved (i.e. the $n^{th}$ trial in the stimulus list must correspond to the $n^{th}$ trial in the response list) and the segments are not too short (they should be at least a few times longer than the duration of your TRF).  Using numpy.array_split on both response and stimulus will not mess up the order:
```python
import numpy as np
stimulus = np.arange(10,20)
response = np.arange(20, 30)
print(stimulus)
print(response)

stimulus = np.array_split(stimulus, 3)
response = np.array_split(response, 3)
print(stimulus)
print(response)
```

**Comment by powerfulbean** [comment]
Following Ole's answer for your first question. The `crossval` is also different from the `train`. `crossval` just accept a single regularization value and call the `_crossval` a single [time,](https://github.com/powerfulbean/mTRFpy/blob/4c163253826d286fda267af49198031c0bc24ada/mtrf/stats.py#L119) while the `train` can accept a list of regularization values and call '_crossval'  multiple [times](https://github.com/powerfulbean/mTRFpy/blob/4c163253826d286fda267af49198031c0bc24ada/mtrf/model.py#L239)  to get result for each regularization value.

**Comment by mamadyonline** [comment]
Thank you very much to both of you. It is now more clearer in my mind. I appreciate the work and hope that it would be around for long (maintained regularly may be the right phrasing).

P.S. Maybe see you at the upcoming CNSP workshops :+1:

**Comment by OleBialas** [comment]
Happy to help and see you at CNSP :)
