### ISSUE TITLE
Multiple channels: get one lambda per channel after optimization ?

### ISSUE THREAD

**Issue by mamadyonline** [powerfulbean/mTRFpy#35]
Hello,

I understand that I can run an mTRF with multiple features (e.g., X with 5 features and 10k samples) and multiple responses (e.g., y with 3 channels and 10k samples). If I want to optmize with multiple lambda values, as of now if I understand correctly, it will optimize accross all the channels and return the best lambda (one value then) for all of them.

Is there a way to optimize the lambdas by channel, ie get one best lambda per channel at the end ?

Thank you !

**Comment by powerfulbean** [comment]
Hi,

Thank you very much for your attention on this package and it is absolutely possible to achieve this ! I am recently testing this feature locally and will push this function soon. Thanks for bringing this up!

Best,
Jin

**Comment by mamadyonline** [comment]
Hello,

Thank you very much for looking into this. I am a fan of the package haha.

Glad to hear it is possible to achieve this feature. Do you think it will add up any constraint on the perfromance, i.e will it run in the same time as of now, or the training will be much slower ?

How long would it take for the feature to be available on master please ? Looking forward to it already xD

Best,
Mamady

**Comment by powerfulbean** [comment]
Hi Mamady,

Glad you like it. It won't slow down the training too much. The part that is affected most is fitting the weights - now we need to fit a projection from input to each channel of the output iteratively with separated regularization parameters. 

I will try to upload the new feature maybe the end of this week!

Best,
Jin

**Comment by mamadyonline** [comment]
HI Jin,

Great ! Looking forward to it already !

Best,
Mamady

**Comment by powerfulbean** [comment]
Hi Mamady,

Thank you so much again for your suggestion of this new feature! I just pushed a preview version of this feature in the [fit_reg_per_chan](https://github.com/powerfulbean/mTRFpy/tree/fit_reg_per_chan) branch. You can try it by pip install that branch:

```sh
pip install git+https://github.com/powerfulbean/mTRFpy.git@fit_reg_per_chan
```
An example of how to using that feature can be found at:
https://github.com/powerfulbean/mTRFpy/blob/e5c357bbd6f17cc9e024fb7472705127eebfdced/tests/test_model.py#L44

I also submitted a pull request #36  to my colleague for necessary code review. Hopefully, the new feature will be merged into the main branch soon!

Best,
Jin

**Comment by powerfulbean** [comment]
> HI Jin,
> 
> Great ! Looking forward to it already !
> 
> Best, Mamady

Hi Mamady,

Thank you so much again for your suggestion of this new feature! I just pushed a preview version of this feature in the [fit_reg_per_chan](https://github.com/powerfulbean/mTRFpy/tree/fit_reg_per_chan) branch. You can try it by pip install that branch:

```sh
pip install git+https://github.com/powerfulbean/mTRFpy.git@fit_reg_per_chan
```
An example of how to using that feature can be found at:
https://github.com/powerfulbean/mTRFpy/blob/e5c357bbd6f17cc9e024fb7472705127eebfdced/tests/test_model.py#L44

I also submitted a pull request #36  to my colleague for necessary code review. Hopefully, the new feature will be merged into the main branch soon!

Best,
Jin

**Comment by mamadyonline** [comment]
Hi Jin,

This is GREAT ! I have tested it and it works like a charm.

I have also lookied at the changes you applied in the code, I was worried in the first place that loop going through each specific channel for training would add an overhead, but it looks like no in fact. 

Thank you very much and keep up the good work !

Best,
Mamady

**Comment by powerfulbean** [comment]
> Hi Jin,
> 
> This is GREAT ! I have tested it and it works like a charm.
> 
> I have also lookied at the changes you applied in the code, I was worried in the first place that loop going through each specific channel for training would add an overhead, but it looks like no in fact.
> 
> Thank you very much and keep up the good work !
> 
> Best, Mamady

Hi Mamady,

No problem! And your point about the overhead is reasonable to me. I am thinking about replacing the training loop with vectorization operation. Will keep you updated in the future!

For now, I will close this issue. Thank you so much for your support!

Best,
Jin
