### ISSUE TITLE
Backward model with one-dimensional feature

### ISSUE THREAD

**Issue by MarliesG** [powerfulbean/mTRFpy#5]
Hi! 

Thanks for making the a python version of mTRF toolbox! 

I would like to address following issue: the backward model is currently not working for one-dimensional features. The basic usage example of the backward model (https://mtrfpy.readthedocs.io/en/latest/basics.html#backward-model) 

```
envelope = [s.mean(axis=1) for s in stimulus]
bwd_trf = TRF(direction=-1)
bwd_trf.train(envelope, response, fs, tmin, tmax, regularization=1000)
r_bwd, mse_bwd = cross_validate(bwd_trf, stimulus, response)
print(f"correlation between actual and predicted envelope: {r_bwd.round(3)}")
```

This code is working. However it uses stimulus (i.e., the spectrogram with 16 frequency band). If you use the same code but replace stimulus with envelope (`r_bwd, mse_bwd = cross_validate(bwd_trf, envelope, response)`), an assertion error occurs (`assert x.ndim == 2 and y.ndim == 2`). By reformatting the shape of the one-dimensional feature (similar to stimulus) different errors popped up. 

Thanks!

**Comment by OleBialas** [comment]
Hey Marlies,
Thanks for catching that bug! I think the error is raised because per default numpy removed the dimension that is averaged. It should work if you replace the first line with 

`envelope = [s.mean(axis=1, keepdims=True) for s in stimulus]`

But the TRF should definitely be able to handle one-dimensional features , I'll look into it

**Comment by OleBialas** [comment]
Also just noticed that there is another error in this example. The `cross_validate` should use `envelope`, not `stimulus` as parameter. I fixed the documentation as well as the dimensions issue, once you download the latest version using pip, it should work. Once you confirmed it works, feel free to close the issue :)

**Comment by MarliesG** [comment]
It works! Thanks!
